{
 "title": "Petshop",
 "description": "Dashboard destinado para as métricas do petshop\n",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nota do atendimento",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pet_shop_score_count{job=\"pet-shop\"}",
     "legendFormat": "Nota do atendimento"
    }
   ]
  },
  {
   "title": "Pessoas na Fila",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pet_shop_pets_in_queue{job=\"pet-shop\"}",
     "legendFormat": "Pessoas na fila"
    }
   ]
  },
  {
   "title": "Pessoas atendidas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pet_shop_total_pets_served", "legendFormat": "Pessoas atendidas" }
   ]
  }
 ]
}